#!/bin/bash

minikube start --cpus 12 --memory 16384 --vm-driver hyperkit
sleep 5
kubectl cluster-info
kubectl create -f spark/dist/conf/kubernetes-resource-staging-server.yaml
sleep 30
kubectl create -f contrib/statefulsets/zookeeper/zookeeper.yaml
sleep 60
kubectl create -f contrib/statefulsets/kafka/kafka.yaml
sleep 60
./createKafkaTopics
sleep 10
kubectl scale statefulset kafka --replicas=1
kubectl proxy