#!/bin/bash

kubectl delete -f contrib/statefulsets/kafka/kafka.yaml
kubectl delete -f contrib/statefulsets/zookeeper/zookeeper.yaml
kubectl delete -f spark/dist/conf/kubernetes-resource-staging-server.yaml
minikube stop
minikube delete