version: '2'

services:
  jupyter:
    image: jupyter/all-spark-notebook:279b14bbdda3
    volumes:
      - .:/home/jovyan/alsad-core:ro
    ports:
      - "8888:8888"

  spark:
    image:  alsad/spark:2.1.0-2.2.0-1-hadoop-2.7

  alsad-dev:
      build:
        context: .
        dockerfile: ./dockerfiles/godev.dockerfile
      image: localhost/godev:1.9-alpine
      working_dir: /go/src/github.com/ALSAD-project/alsad-core
      volumes:
        - .:/go/src/github.com/ALSAD-project/alsad-core

  expertsystem-daemon:
    build:
      context: .
      dockerfile: ./dockerfiles/expertsystem.daemon.dockerfile
    image: localhost/expertsystem
    environment:
      - PORT=4000
      - HOSTNAME=0.0.0.0
      - SOURCE_DIRECTORY=tmp/input/
      - DESTINATION_DIRECTORY=tmp/input/
    ports:
      - "4000:4000"

  expertsystem-terminal:
    build:
      context: .
      dockerfile: ./dockerfiles/expertsystem.terminal.dockerfile
    image: localhost/expertsystem
    environment:
      - PORT=4000
      - HOSTNAME=expertsystem-daemon
      - SOURCE_DIRECTORY=tmp/input/
      - DESTINATION_DIRECTORY=tmp/input/
