version: '2'

services:
  jupyter:
    image: jupyter/all-spark-notebook:279b14bbdda3
    volumes:
      - .:/home/jovyan/alsad-core:ro
    ports:
      - "8888:8888"

  spark:
    image:  alsad/spark:2.1.0-2.2.0-1-hadoop-2.7

  expertsystem-daemon:
    build:
      context: .
      dockerfile: ./dockerfiles/expertsystem.daemon.dockerfile
    image: localhost/expertsystem
    environment:
      - ES_DAEMON_PORT=4000
      - ES_SRC_DIR=tmp/input/
      - ES_DEST_DIR=tmp/output/
    ports:
      - "4000:4000"

  expertsystem-terminal:
    build:
      context: .
      dockerfile: ./dockerfiles/expertsystem.terminal.dockerfile
    image: localhost/expertsystem
    environment:
      - ES_DAEMON_PORT=4000
      - ES_DAEMON_HOST=expertsystem-daemon
      - ES_SRC_DIR=tmp/input/
      - ES_DEST_DIR=tmp/output/